//@ts-ignore
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "NSS IIIT-H",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
          /* Hide scrollbars for all elements */
          html, body, * {
            scrollbar-width: none !important; /* Firefox */
            -ms-overflow-style: none !important; /* IE 10+ */
          }
          ::-webkit-scrollbar {
            display: none !important; /* Chrome, Safari, Opera */
          }
        `}</style>
      </head>
      <body
        style={{
          margin: 0,
          padding: 0,
          overflowX: "hidden"
        }}
      >
        {children}
      </body>
    </html>
  );
}
