const members = [
  {
    id: "2025115003",
    email: "aakanksha.vulugonda@research.iiit.ac.in",
    name: "Vulugonda Aakanksha",
    photoUrl: "",
    team: "Community",
    rollNumber: "2025115003",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2024115008",
    email: "akshat.sharma@research.iiit.ac.in",
    name: "Akshat Sharma",
    photoUrl: "",
    team: "Community",
    rollNumber: "2024115008",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2023101023",
    email: "anvithraj.basani@students.iiit.ac.in",
    name: "Anvithraj Reddy Basani",
    photoUrl: "",
    team: "Community",
    rollNumber: "2023101023",
    status: "active" as "active",
    from: "2024",
    to: ""
  },
  {
    id: "2025101033",
    email: "avinash.muthoju@students.iiit.ac.in",
    name: "Muthoju Avinash",
    photoUrl: "",
    team: "Community",
    rollNumber: "2025101033",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2023101044",
    email: "bakaram.charan@students.iiit.ac.in",
    name: "Bakaram Sai Charan",
    photoUrl: "",
    team: "Community",
    rollNumber: "2023101044",
    status: "active" as "active",
    from: "2024",
    to: ""
  },
  {
    id: "2024102014",
    email: "chanda.kumar@students.iiit.ac.in",
    name: "Chanda Akshay Kumar",
    photoUrl: "",
    team: "Tech",
    rollNumber: "2024102014",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2025102044",
    email: "chandrahas.n@students.iiit.ac.in",
    name: "Chandrahas Nandibhatla",
    photoUrl: "",
    team: "Community",
    rollNumber: "2025102044",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2025102040",
    email: "divijat.somani@students.iiit.ac.in",
    name: "Divijat Somani",
    photoUrl: "",
    team: "Design",
    rollNumber: "2025102040",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2024101113",
    email: "hemanthkumar.m@students.iiit.ac.in",
    name: "Madathanapalli Hemanth Kumar",
    photoUrl: "",
    team: "Community",
    rollNumber: "2024101113",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2025102058",
    email: "ishant.mahajan@students.iiit.ac.in",
    name: "Ishant Mahajan",
    photoUrl: "",
    team: "Community",
    rollNumber: "2025102058",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2023101025",
    email: "jaswanthreddy.k@students.iiit.ac.in",
    name: "Konapalli Jaswanth Reddy",
    photoUrl: "",
    team: "Community",
    rollNumber: "2023101025",
    status: "active" as "active",
    from: "2024",
    to: ""
  },
  {
    id: "2024101102",
    email: "jetty.sairam@students.iiit.ac.in",
    name: "Jetty Jithendra Sai Ram",
    photoUrl: "",
    team: "Community",
    rollNumber: "2024101102",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2025101065",
    email: "kandhivanam.bhavagna@students.iiit.ac.in",
    name: "Kandhivanam Bhavagna",
    photoUrl: "",
    team: "Community",
    rollNumber: "2025101065",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2025101099",
    email: "kanishka.sagili@students.iiit.ac.in",
    name: "Sagili Kanishka",
    photoUrl: "",
    team: "Community",
    rollNumber: "2025101099",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2025113008",
    email: "kattagani.haasini@research.iiit.ac.in",
    name: "Kattagani Haasini",
    photoUrl: "",
    team: "Community",
    rollNumber: "2025113008",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2024101066",
    email: "maddhipatla.devi@students.iiit.ac.in",
    name: "Maddhipatla Sowjanya Devi",
    photoUrl: "",
    team: "Community",
    rollNumber: "2024101066",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2023101022",
    email: "manitej.sriram@students.iiit.ac.in",
    name: "Sriram Mani Tej",
    photoUrl: "",
    team: "Tech",
    rollNumber: "2023101022",
    status: "active" as "active",
    from: "2024",
    to: ""
  },
  {
    id: "2024111030",
    email: "navneet.gupta@research.iiit.ac.in",
    name: "Navneet Kumar Gupta",
    photoUrl: "",
    team: "Community",
    rollNumber: "2024111030",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2024113023",
    email: "neharika.rajesh@research.iiit.ac.in",
    name: "Neharika Rajesh",
    photoUrl: "",
    team: "Tech",
    rollNumber: "2024113023",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2023102013",
    email: "nethavath.praveen@students.iiit.ac.in",
    name: "Nethavath Praveen",
    photoUrl: "",
    team: "Community",
    rollNumber: "2023102013",
    status: "active" as "active",
    from: "2024",
    to: ""
  },
  {
    id: "2024102047",
    email: "nethi.padmanjali@students.iiit.ac.in",
    name: "N Padmanjali",
    photoUrl: "",
    team: "Design",
    rollNumber: "2024102047",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2024114003",
    email: "nikhita.ravi@research.iiit.ac.in",
    name: "Nikhita Anjani Ravi",
    photoUrl: "",
    team: "Design",
    rollNumber: "2024114003",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2024101076",
    email: "pashya.chervith@students.iiit.ac.in",
    name: "Pashya Chervith Reddy",
    photoUrl: "",
    team: "Community",
    rollNumber: "2024101076",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2025121016",
    email: "poreddy.reddy@research.iiit.ac.in",
    name: "Poreddy Srivatsav Reddy",
    photoUrl: "",
    team: "Tech",
    rollNumber: "2025121016",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2025101028",
    email: "pranathi.giri@students.iiit.ac.in",
    name: "Giri Pranathi",
    photoUrl: "",
    team: "Design",
    rollNumber: "2025101028",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2024101106",
    email: "pranathi.koppolu@students.iiit.ac.in",
    name: "Koppolu Pranathi Sindhu",
    photoUrl: "",
    team: "Community",
    rollNumber: "2024101106",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2023102032",
    email: "radheshyam.modampuri@students.iiit.ac.in",
    name: "Modampuri Radheshyam",
    photoUrl: "",
    team: "Community",
    rollNumber: "2023102032",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2024102005",
    email: "rithik.palla@students.iiit.ac.in",
    name: "Rithik Reddy Palla",
    photoUrl: "",
    team: "Tech",
    rollNumber: "2024102005",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2024102017",
    email: "sangameshwar.sale@students.iiit.ac.in",
    name: "Sale Sangameshwar",
    photoUrl: "",
    team: "Tech",
    rollNumber: "2024102017",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2024102055",
    email: "sindhuja.babu@students.iiit.ac.in",
    name: "Sindhuja Babu",
    photoUrl: "",
    team: "Design",
    rollNumber: "2024102055",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2025101030",
    email: "subhasree.sahoo@students.iiit.ac.in",
    name: "Subhasree Subhalaxmi Sahoo",
    photoUrl: "",
    team: "Community",
    rollNumber: "2025101030",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2023101012",
    email: "sudheer.chatla@students.iiit.ac.in",
    name: "Chatla Sudheer",
    photoUrl: "",
    team: "Design",
    rollNumber: "2023101012",
    status: "active" as "active",
    from: "2024",
    to: ""
  },
  {
    id: "2023101067",
    email: "sukasi.manidhar@students.iiit.ac.in",
    name: "Sukasi Manidhar",
    photoUrl: "",
    team: "Community",
    rollNumber: "2023101067",
    status: "active" as "active",
    from: "2024",
    to: ""
  },
  {
    id: "2024102074",
    email: "sukeerthi.kattamuri@students.iiit.ac.in",
    name: "Sukeerthi Kattamuri",
    photoUrl: "",
    team: "Design",
    rollNumber: "2024102074",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2023115007",
    email: "t.goud@research.iiit.ac.in",
    name: "T Lokesh Goud",
    photoUrl: "",
    team: "Community",
    rollNumber: "2023115007",
    status: "active" as "active",
    from: "2024",
    to: ""
  },
  {
    id: "2024115010",
    email: "tharani.perumalla@research.iiit.ac.in",
    name: "Perumalla Tharani Theertha",
    photoUrl: "",
    team: "Tech",
    rollNumber: "2024115010",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2023101100",
    email: "vastava.kurumeti@students.iiit.ac.in",
    name: "Kurumeti Sri Sai Nikhil Sri Vastava",
    photoUrl: "",
    team: "Design",
    rollNumber: "2023101100",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2024117008",
    email: "veena.ramadas@research.iiit.ac.in",
    name: "Veena Vadakkathmana Ramadas",
    photoUrl: "",
    team: "Tech",
    rollNumber: "2024117008",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2024101009",
    email: "vineelsaireddy.s@students.iiit.ac.in",
    name: "Somannagari Vineel Sai Reddy",
    photoUrl: "",
    team: "Community",
    rollNumber: "2024101009",
    status: "active" as "active",
    from: "2025",
    to: ""
  },
  {
    id: "2025102028",
    email: "vuddagiri.anukruthi@students.iiit.ac.in",
    name: "Vuddagiri Anukruthi",
    photoUrl: "",
    team: "Community",
    rollNumber: "2025102028",
    status: "active" as "active",
    from: "2025",
    to: ""
  }
];

export default members;